// <auto-generated />
using System;
using GameZenCritic.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameZenCritic.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GameZenDbContext))]
    [Migration("20240226142041_newSeed")]
    partial class newSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifying key");

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Rating for recommended age (usually by ESRB)");

                    b.Property<string>("AgeRatingPicture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Link to picture of age rating for the game");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Detailed info of the game");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The game developer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Deletion flag");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)")
                        .HasComment("Name of the game");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Link to picture of box art for the game");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date of the game initial release");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Average total score of reviews for the game");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasComment("Game list including description and various info");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0843ecf-38cf-4a72-a383-2b1c3c0d8d02"),
                            AgeRating = "Rated M for Mature",
                            AgeRatingPicture = "https://www.metacritic.com/a/neutron/images/logos/esrb/ESRB_2013_M_Rating.png",
                            Description = "Gears of War blends tactical action with survival horror and thrusts gamers into a deep and harrowing story of humankind's epic battle for survival against the Locust Horde, a nightmarish race of creatures that surface from the bowels of the planet.",
                            Developer = "Epic Games",
                            IsDeleted = false,
                            Name = "Gears of War",
                            Picture = "https://www.metacritic.com/a/img/resize/c2c2122b8f2a30ff7dacbdf98d3091c0a9f8088c/catalog/provider/6/12/6-1-68349-52.jpg",
                            ReleaseDate = new DateTime(2006, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalScore = 8m
                        },
                        new
                        {
                            Id = new Guid("b16e5fc7-1fcd-48e8-ae77-6cf139b0b647"),
                            AgeRating = "Rated M for Mature",
                            AgeRatingPicture = "https://www.metacritic.com/a/neutron/images/logos/esrb/ESRB_2013_M_Rating.png",
                            Description = "A New World Created By Hidetaka Miyazaki And George R. R. Martin ELDEN RING, developed by FromSoftware, Inc. and BANDAI NAMCO Entertainment Inc.",
                            Developer = "From Software",
                            IsDeleted = false,
                            Name = "Elden Ring",
                            Picture = "https://www.metacritic.com/a/img/resize/a7d9a5a01234b361785789476e073076a29dad5b/catalog/provider/6/3/6-1-824862-13.jpg",
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalScore = 9.5m
                        },
                        new
                        {
                            Id = new Guid("7f1e9d4b-53a8-4e63-9d23-31f48a11c41e"),
                            AgeRating = "Rated M for Mature",
                            AgeRatingPicture = "https://www.metacritic.com/a/neutron/images/logos/esrb/ESRB_2013_M_Rating.png",
                            Description = "An ancient evil has returned to Baldur's Gate, intent on devouring it from the inside out. The fate of Faerun lies in your hands. Alone, you may resist. But together, you can overcome.",
                            Developer = "Larian Studios Games",
                            IsDeleted = false,
                            Name = "Baldur's Gate 3",
                            Picture = "https://www.metacritic.com/a/img/resize/04973a32611600dace99c3638bd3b8f6a9e09477/catalog/provider/7/2/7-1695438055.jpg",
                            ReleaseDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalScore = 9.3m
                        },
                        new
                        {
                            Id = new Guid("3e33c5e3-ec4f-4b31-93b0-686fd2da6314"),
                            AgeRating = "Rated M for Mature",
                            AgeRatingPicture = "https://www.metacritic.com/a/neutron/images/logos/esrb/ESRB_2013_M_Rating.png",
                            Description = "With the Empire attacking the Kingdoms of the North and the Wild Hunt, a cavalcade of ghastly riders, breathing down your neck, the only way to survive is to fight back. As Geralt of Rivia, a master swordsman and monster hunter, leave none of your enemies standing.",
                            Developer = "CD Projekt Red Studio",
                            IsDeleted = false,
                            Name = "The Witcher 3: Wild Hunt",
                            Picture = "https://pre00.deviantart.net/e81c/th/pre/f/2014/157/f/9/witcher_3_box_cover_warner_bros_variation_by_scratcherpen-d7l8i4h.png",
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalScore = 9.0m
                        },
                        new
                        {
                            Id = new Guid("a8bf3a6e-509d-497b-92a7-f2c4d0f81b5b"),
                            AgeRating = "Rated M for Mature",
                            AgeRatingPicture = "https://www.metacritic.com/a/neutron/images/logos/esrb/ESRB_2013_M_Rating.png",
                            Description = "The freezing winds of Fimbulwinter have come to Midgard, making survival for Kratos, Atreus, and Mimir in the Norse wilds even more challenging than before. ",
                            Developer = "SCE Santa Monica",
                            IsDeleted = false,
                            Name = "God of War: Ragnarok",
                            Picture = "https://www.metacritic.com/a/img/resize/ca0bc42afe883be3a8bac27a19cf2f972fb07921/catalog/provider/6/3/6-1-905093-13.jpg",
                            ReleaseDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalScore = 8.1m
                        });
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.GamePlatform", b =>
                {
                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasComment("Platform key");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Game key");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Deletion flag");

                    b.HasKey("PlatformId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GamesPlatforms");

                    b.HasComment("List of the games and platforms, many to many related");

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            GameId = new Guid("f0843ecf-38cf-4a72-a383-2b1c3c0d8d02"),
                            IsDeleted = false
                        },
                        new
                        {
                            PlatformId = 2,
                            GameId = new Guid("f0843ecf-38cf-4a72-a383-2b1c3c0d8d02"),
                            IsDeleted = false
                        },
                        new
                        {
                            PlatformId = 1,
                            GameId = new Guid("b16e5fc7-1fcd-48e8-ae77-6cf139b0b647"),
                            IsDeleted = false
                        },
                        new
                        {
                            PlatformId = 3,
                            GameId = new Guid("b16e5fc7-1fcd-48e8-ae77-6cf139b0b647"),
                            IsDeleted = false
                        },
                        new
                        {
                            PlatformId = 4,
                            GameId = new Guid("b16e5fc7-1fcd-48e8-ae77-6cf139b0b647"),
                            IsDeleted = false
                        },
                        new
                        {
                            PlatformId = 1,
                            GameId = new Guid("7f1e9d4b-53a8-4e63-9d23-31f48a11c41e"),
                            IsDeleted = false
                        },
                        new
                        {
                            PlatformId = 3,
                            GameId = new Guid("7f1e9d4b-53a8-4e63-9d23-31f48a11c41e"),
                            IsDeleted = false
                        },
                        new
                        {
                            PlatformId = 4,
                            GameId = new Guid("7f1e9d4b-53a8-4e63-9d23-31f48a11c41e"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identifying key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Deletion flag");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the Genre");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasComment("The genre of the game e.g. Action, Adventure etc.");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Third Person Shooter"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Action RPG"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Western RPG"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Action Adventure"
                        });
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.GenreGame", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("Genre key/identifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Game key/identifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Deletion flag");

                    b.HasKey("GenreId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GenresGames");

                    b.HasComment("List of the games and genres, many to many related");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GameId = new Guid("f0843ecf-38cf-4a72-a383-2b1c3c0d8d02"),
                            IsDeleted = false
                        },
                        new
                        {
                            GenreId = 2,
                            GameId = new Guid("b16e5fc7-1fcd-48e8-ae77-6cf139b0b647"),
                            IsDeleted = false
                        },
                        new
                        {
                            GenreId = 3,
                            GameId = new Guid("7f1e9d4b-53a8-4e63-9d23-31f48a11c41e"),
                            IsDeleted = false
                        },
                        new
                        {
                            GenreId = 3,
                            GameId = new Guid("3e33c5e3-ec4f-4b31-93b0-686fd2da6314"),
                            IsDeleted = false
                        },
                        new
                        {
                            GenreId = 4,
                            GameId = new Guid("a8bf3a6e-509d-497b-92a7-f2c4d0f81b5b"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Platform identifier key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Deletion flag");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Platform name");

                    b.HasKey("Id");

                    b.ToTable("Platform");

                    b.HasComment("Platform list inclusing identifier and name");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Xbox 360"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "PlayStation 5"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Xbox Series X"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "PlayStation 4"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Xbox One"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Nintendo Switch"
                        });
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.PlayerGameReview", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Player key/identifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Game key/identifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Text info for the review");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Deletion flag");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasComment("The score for the game on this review 0-10");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("PlayersGamesReviews");

                    b.HasComment("The reviews from each player for each game including score and details");

                    b.HasData(
                        new
                        {
                            PlayerId = "dea12856-c198-4129-b3f3-b893d8395085",
                            GameId = new Guid("b16e5fc7-1fcd-48e8-ae77-6cf139b0b647"),
                            Details = "This is the greatest game ever made!",
                            IsDeleted = false,
                            Score = 10
                        },
                        new
                        {
                            PlayerId = "dea12856-c198-4129-b3f3-b893d8395085",
                            GameId = new Guid("f0843ecf-38cf-4a72-a383-2b1c3c0d8d02"),
                            Details = "Was an OK shooter, but overhyped.",
                            IsDeleted = false,
                            Score = 7
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.Player", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("Player");

                    b.HasData(
                        new
                        {
                            Id = "dea12856-c198-4129-b3f3-b893d8395085",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ac54ea67-d2ca-45ad-9279-040b0beb2676",
                            Email = "player@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "player@mail.com",
                            NormalizedUserName = "player@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEAo5RWB3br/HhXzTFs6QmBTZd5/d2TqFNiBvjqNROL1XMlKJPT8ug243oO9BAAqG4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3268723d-62b6-415a-a85e-a08f966d3594",
                            TwoFactorEnabled = false,
                            UserName = "player@mail.com"
                        },
                        new
                        {
                            Id = "fea12856-c198-4129-b3f3-b893d8395080",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05f9a610-8a85-4885-b00a-b08f0682a58b",
                            Email = "player2@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "player2@mail.com",
                            NormalizedUserName = "player2@mail.com",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18cb07a2-f21b-44d8-8982-f6a56e43e94b",
                            TwoFactorEnabled = false,
                            UserName = "player2@mail.com"
                        });
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.GamePlatform", b =>
                {
                    b.HasOne("GameZenCritic.Infrastructure.Data.Models.Game", "Game")
                        .WithMany("GamesPlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GameZenCritic.Infrastructure.Data.Models.Platform", "Platform")
                        .WithMany("GamesPlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.GenreGame", b =>
                {
                    b.HasOne("GameZenCritic.Infrastructure.Data.Models.Game", "Game")
                        .WithMany("GenresGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GameZenCritic.Infrastructure.Data.Models.Genre", "Genre")
                        .WithMany("GenresGames")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.PlayerGameReview", b =>
                {
                    b.HasOne("GameZenCritic.Infrastructure.Data.Models.Game", "Game")
                        .WithMany("PlayersGamesReviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GameZenCritic.Infrastructure.Data.Models.Player", "Player")
                        .WithMany("PlayersGamesReviews")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.Game", b =>
                {
                    b.Navigation("GamesPlatforms");

                    b.Navigation("GenresGames");

                    b.Navigation("PlayersGamesReviews");
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.Genre", b =>
                {
                    b.Navigation("GenresGames");
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.Platform", b =>
                {
                    b.Navigation("GamesPlatforms");
                });

            modelBuilder.Entity("GameZenCritic.Infrastructure.Data.Models.Player", b =>
                {
                    b.Navigation("PlayersGamesReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
